[package]
name = "nanite-factory-game-map"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version = "0.15.3", features = ["dynamic_linking"]}
bevy_ecs_tilemap = "0.15.0"
bevy_pancam = "0.17.0"
bevy_picking_tilemap = { git = "https://github.com/daniel-brenot/bevy_picking_tilemap.git", branch = "master" }
bevy_quick_response = "0.3.1"
bevy_rapier2d = "0.29.0"
crossbeam-channel = "0.5.14"
thiserror = "2.0.12"
tiled = "0.14.0"

[features]
atlas = ["bevy_ecs_tilemap/atlas"]
render = ["bevy_ecs_tilemap/render"]
