[package]
name = "nanite-factory-map"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version = "0.15.3", features = ["dynamic_linking"]}
bevy_ecs_tilemap = "0.15.0"
thiserror = "2.0.12"
tiled = "0.14.0"

[features]
atlas = ["bevy_ecs_tilemap/atlas"]
render = ["bevy_ecs_tilemap/render"]