[package]
name = "nanite-factory-game-map"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 1

# Enable a large amount of optimization in the dev profile for dependencies.
[profile.dev.package."*"]
opt-level = 3

[dependencies]
bevy = {version = "0.15.3", features = ["dynamic_linking", "wayland"]}
bevy_ecs_tilemap = "0.15.0"
bevy_pancam = "0.17.0"
bevy_picking_tilemap = { git = "https://github.com/daniel-brenot/bevy_picking_tilemap.git", branch = "master" }
bevy_aseprite = { git = "https://github.com/daniel-brenot/bevy_aseprite.git", branch = "bevy-0.15"}
bevy_quick_response = "0.3.1"
crossbeam-channel = "0.5.14"
thiserror = "2.0.12"
tiled = "0.14.0"
bevy_tweening = "0.12.0"
wasm-streams = "0.4.2"
wasm-bindgen = "0.2.100"
serde = "1.0.219"
serde-wasm-bindgen = "0.6.5"
bevy_mod_sysfail = { git="https://github.com/daniel-brenot/bevy_mod_sysfail.git", branch="main"}
anyhow = "1.0.98"
tracing-wasm = "0.2.1"
tracing = "0.1.41"

[features]
default = ["atlas", "render"]
atlas = ["bevy_ecs_tilemap/atlas"]
render = ["bevy_ecs_tilemap/render"]