[package]
name = "generate_frames"
version = "0.1.0"
edition = "2024"

[dependencies]
bevy = "0.15.3"
pathfinding = "4.14.0"
serde = { version="1.0.219", features = ["derive"] }
serde_json = "1.0.140"
tiled = "0.14.0"
